[package]
name = "nalgebra-euler"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.21.0"
alga = "0.9.2"

[dev-dependencies]
assert_approx_eq = "1.1.0"
